### ISSUE TITLE
Improvement: make it clear how to select multiple repos

### ISSUE THREAD

**Issue by adrianmg** [adrianmg/github-pewpew#29] opened 2022-04-04 05:22 UTC
Some users get confused when trying to select a repository from the list, as they'd use `INTRO` instead of `SPACE BAR` to select. I could make that more obvious with an instruction

**Comment by arisacoba** [comment] 2022-04-04 06:50
Oof, I think my issue was a duplicate of this https://github.com/adrianmg/github-pewpew/issues/31 😅

**Closed** 2022-04-25 18:45 UTC
Labels: enhancement
